#lang racket
(begin
  (require "./gd-script-classes.rkt"))
(begin
  (provide Object)
  (gd-api-class Object
                object%
                ((get_class) (is_class class)
                             (set property value)
                             (get property)
                             (set_indexed property_path value)
                             (get_indexed property_path)
                             (get_property_list)
                             (get_method_list)
                             (property_can_revert property)
                             (property_get_revert property)
                             (notification what reversed)
                             (to_string)
                             (get_instance_id)
                             (set_script script)
                             (get_script)
                             (set_meta name value)
                             (remove_meta name)
                             (get_meta name default)
                             (has_meta name)
                             (get_meta_list)
                             (add_user_signal signal arguments)
                             (has_user_signal signal)
                             (emit_signal signal)
                             (call method)
                             (call_deferred method)
                             (set_deferred property value)
                             (callv method arg_array)
                             (has_method method)
                             (has_signal signal)
                             (get_signal_list)
                             (get_signal_connection_list signal)
                             (get_incoming_connections)
                             (connect signal callable flags)
                             (disconnect signal callable)
                             (is_connected signal callable)
                             (set_block_signals enable)
                             (is_blocking_signals)
                             (notify_property_list_changed)
                             (set_message_translation enable)
                             (can_translate_messages)
                             (tr message context)
                             (tr_n message plural_message n context)
                             (is_queued_for_deletion)
                             (cancel_free))
                ()
                (godot-object-mixin))
  (provide Object:ConnectFlags:CONNECT_REFERENCE_COUNTED)
  (define-syntax (Object:ConnectFlags:CONNECT_REFERENCE_COUNTED stx) (syntax 8))
  (provide Object:ConnectFlags:CONNECT_ONE_SHOT)
  (define-syntax (Object:ConnectFlags:CONNECT_ONE_SHOT stx) (syntax 4))
  (provide Object:ConnectFlags:CONNECT_PERSIST)
  (define-syntax (Object:ConnectFlags:CONNECT_PERSIST stx) (syntax 2))
  (provide Object:ConnectFlags:CONNECT_DEFERRED)
  (define-syntax (Object:ConnectFlags:CONNECT_DEFERRED stx) (syntax 1)))
(begin
  (provide RefCounted)
  (gd-api-class RefCounted Object ((init_ref) (reference) (unreference) (get_reference_count)) ()))